CREATE TABLE notes (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title   VARCHAR(200)   NOT NULL,
    content VARCHAR(10000),
    user_id BIGINT         NOT NULL,
    CONSTRAINT fk_notes_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_notes_user_id ON notes (user_id);
