CREATE TABLE refresh_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash  VARCHAR(64) NOT NULL UNIQUE,
    expiry_date TIMESTAMP   NOT NULL,
    revoked_at  TIMESTAMP,
    user_id     BIGINT      NOT NULL,
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_refresh_tokens_user_active ON refresh_tokens (user_id, revoked_at);
